qstnrs/qstnrs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^qstnrs/', include('questionnaire.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

qstnrs/questionnaire/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'questionnaire.views',
    url(r'^$', 'index', name='qstnrs-index'),
    url(r'^(?P<questionnaire_id>\d+)/(?P<page_id>\d+)/$', 'page',
        name='qstnrs-page'),
    url(r'^(?P<questionnaire_id>\d+)/$', 'page_without_id',
        name='qstnrs-page-no-id'),
    url(r'^result/(?P<questionnaire_id>\d+)/$', 'result', name='qstnrs-result')
)

qstnrs/questionnaire/models.py
from django.db import models


class Questionnaire(models.Model):
    questionnaire_name = models.CharField(max_length=150)
    questionnaire_description = models.TextField(max_length=500)

    def __unicode__(self):
        return self.questionnaire_name[:100]

    class Meta:
        ordering = ['questionnaire_name']


class Page(models.Model):
    questionnaire = models.ForeignKey(Questionnaire)
    page_name = models.CharField(max_length=50)

    class Meta:
        order_with_respect_to = 'questionnaire'

    def __unicode__(self):
        return self.page_name


class Question(models.Model):
    page = models.ForeignKey(Page)
    question_text = models.CharField(max_length=250)

    def __unicode__(self):
        return self.question_text[:100]

    class Meta:
        order_with_respect_to = 'page'


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=50)
    answer_score = models.IntegerField()

    def __unicode__(self):
        return self.answer_text

qstnrs/questionnaire/forms.py
from django import forms


class PageForm(forms.Form):
    def __init__(self, *args, **kwargs):
        page = kwargs.pop('page')
        super(PageForm, self).__init__(*args, **kwargs)

        for question in page.question_set.values(
                'id', 'question_text', 'answer', 'answer__answer_text'):
            field_key = 'question_%s' % question['id']

            self.fields.setdefault(field_key, forms.MultipleChoiceField(
                choices=[],
                label=question['question_text']))

            self.fields[field_key].choices.append(
                (question['answer'], question['answer__answer_text']))

qstnrs/questionnaire/views.py
from questionnaire.models import Page, Question, Questionnaire
from questionnaire.forms import PageForm
from questionnaire.utils import get_score_for, get_suggestions_for,\
    get_max_score_for
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    paginator = Paginator(Questionnaire.objects.all(), 3)
    try:
        questionnaire_page = request.GET.get('page')
    except KeyError:
        raise Http404

    if 'choices' in request.session:
        del request.session['choices']

    try:
        questionnaires = paginator.page(questionnaire_page)
    except PageNotAnInteger:
        questionnaires = paginator.page(1)
    except EmptyPage:
        questionnaires = paginator.page(paginator.num_pages)

    return render(request, "main.html",
                  {"questionnaires": questionnaires})


def page_without_id(request, questionnaire_id):
    try:
        first_page = Page.objects.filter(
            questionnaire_id=questionnaire_id)[0].id
        url = reverse('qstnrs-page', args=(questionnaire_id, first_page))
    except IndexError:
        url = reverse('qstnrs-index')

    return HttpResponseRedirect(url)


def page(request, questionnaire_id, page_id):
    # Get current page
    current_page = get_object_or_404(Page, id=page_id)

    page_has_questions = Question.objects.filter(
        page_id=page_id
    ).count() > 0

    # current_page = get_object_or_404(page_list, id=page_id)
    # Get next page id, if there isn't one, display the View Results button
    try:
        next_page_id = current_page.get_next_in_order().id
    except Page.DoesNotExist:
        next_page_id = -1
    # Get previous page id, if there isn't one, hide the Previous Page
    # button
    try:
        previous_page_id = current_page.get_previous_in_order().id
    except Page.DoesNotExist:
        previous_page_id = -1

    if request.method == 'POST':
        form = PageForm(request.POST, page=current_page)
        if form.is_valid():
            request.session.setdefault('choices', [])
            request.session['choices'] += [
                int(choice_id)
                for value in form.cleaned_data.values()
                for choice_id in value]

            if 'previousPage' in request.POST:
                goto_page = previous_page_id
            elif 'nextPage' in request.POST:
                goto_page = next_page_id
            elif 'viewResults' in request.POST:
                return HttpResponseRedirect(
                    reverse('qstnrs-result', args=(questionnaire_id,)))
            return HttpResponseRedirect(
                reverse('qstnrs-page',
                        args=(questionnaire_id, goto_page)))
    else:
        form = PageForm(page=current_page)

    return render(request, "page.html", {
        "form": form,
        "page_has_questions": page_has_questions,
        "has_previous": previous_page_id > -1,
        "has_next": next_page_id > -1,
        "questionnaire_id": questionnaire_id
    })


def result(request, questionnaire_id):
    user_choices = request.session['choices']
    user_score = get_score_for(user_choices)
    max_score = get_max_score_for(questionnaire_id)

    better_suggestions = get_suggestions_for(
        questionnaire_id, user_choices, better=True
    )
    worse_suggestions = get_suggestions_for(
        questionnaire_id, user_choices, better=False
    )

    try:
        questionnaire = Questionnaire.objects.get(id=questionnaire_id)
    except Questionnaire.DoesNotExist:
        questionnaire = None

    del request.session['choices']
    return render(request, "result.html", {
        "user_score": user_score,
        "max_score": max_score,
        "questionnaire": questionnaire,
        "better_suggestions": better_suggestions,
        "worse_suggestions": worse_suggestions
    })

qstnrs/questionnaire/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'questionnaire/css/style.css' %}">
    <title>{% block title %}Questionnaire{% endblock %}</title>
</head>
<body>
    {% block extrainfo %}{% endblock %}
    <div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

qstnrs/questionnaire/templates/index.html
{% if questionnaire_list %}
    List of questionnaires:
    <ul>
        {% for questionnaire in questionnaire_list %}
            <li>
                <a href="/qstnrs/{{ questionnaire.id }}/{{ questionnaire.first_page_id }}">{{ questionnaire.name }}</a> --- {{ questionnaire.description }}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Questionnaires available.</p>
{%  endif %}

qstnrs/questionnaire/templates/main.html
{% extends "base.html" %}

{% block title %}Questionnaire List{% endblock %}

{% block content %}
    List of questionnaires:
    <ul>
        {% for questionnaire in questionnaires %}
            <li>
            {% if questionnaire.page_set.count > 0 %}
                <a href="{% url qstnrs-page-no-id questionnaire.id %}">
                    {{ questionnaire.questionnaire_name }}</a> --- {{ questionnaire.questionnaire_description }}
            {% else %}
                {{ questionnaire.questionnaire_name }} --- {{ questionnaire.questionnaire_description }}
            {% endif %}
            </li>
        {% empty %}
            <p>No Questionnaires available.</p>
        {% endfor %}
    </ul>

<div class="pagination">
    <span class="step-links">
        {% if questionnaires.has_previous %}
            <a href="?page={{ questionnaires.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current-page">
            Page {{ questionnaires.number }} of {{ questionnaires.paginator.num_pages }}
        </span>

        {% if questionnaires.has_next %}
            <a href="?page={{ questionnaires.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

qstnrs/questionnaire/templates/page.html
{% extends "base.html" %}

{% block title %}Questionnaire{% endblock %}

{% block content %}
    {% if not page_has_questions %}
        <header>This page has no questions available.</header><br>
    {% endif %}
    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}

        {% if has_previous %}
            <input type="submit" name="previousPage" value="Previous Page" />
        {% endif %}

        {% if has_next %}
            <input type="submit" name="nextPage" value="Next Page" />
        {% endif %}
        {% if has_previous and not has_next %}
            <input type="submit" name="viewResults" value="View Results" />
        {% endif %}
        {% if not has_previous and not has_next %}
            <footer><a href={% url qstnrs-index %}>Back to Questionnaires list</a></footer>
        {% endif %}
    </form>
{% endblock %}

qstnrs/questionnaire/templates/result.html
{% extends "base.html" %}

{% block title %}Questionnaire Result{% endblock %}

{% block extrainfo %}
    Your score: {{ user_score }} out of {{ max_score }}<br>
{% endblock %}

{% block content %}
    {% if better_suggestions %}
        For an improved score you could have selected: <br>
        {% for answer in better_suggestions %}
            Q: {{ answer.question.question_text }} <br>
            A: {{ answer.answer_text }}
        {% endfor %}
    {% endif %}
    {% if worse_suggestions %}
        <br>For a worse score you could have selected: <br>
        {% for answer in worse_suggestions %}
            Q: {{ answer.question.question_text }} <br>
            A: {{ answer.answer_text }}
        {% endfor %}
    {% endif %}
    {% if not better_suggestions and not worse_suggestions %}
        No extra selections possible.
    {% endif %}
    <footer>
        <a href={% url qstnrs-index %}>Back to Questionnaires list</a>
    </footer>
{% endblock %}